version: '3.8'

services:
  streaming-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cmsms-app
    ports:
      - "80:80"
    volumes:
      - ./cmsms-data:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=512M
    depends_on:
      - streaming-manager-db

  streaming-manager-db:
    image: mariadb:10.5
    container_name: streaming-manager-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cmsms_db
      MYSQL_USER: cmsms_user
      MYSQL_PASSWORD: cmsms_password
    volumes:
      - streaming-manager-db-data:/var/lib/mysql
    platform: linux/arm64

volumes:
  streaming-manager-db-data:
